/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import javax.swing.JOptionPane;

/**
 *
 * @author raico
 */
public class CancelClass extends javax.swing.JFrame {

    /**
     * Creates new form CancelClass
     */
    public CancelClass() {
        initComponents();
		        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        body = new javax.swing.JRadioButton();
        bootcamp = new javax.swing.JRadioButton();
        zumba = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        AM = new javax.swing.JRadioButton();
        PM = new javax.swing.JRadioButton();
        spinning = new javax.swing.JRadioButton();
        ABS = new javax.swing.JRadioButton();
        cardio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/IMG/cancel class.JPG"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancel.setBackground(new java.awt.Color(139, 184, 139));
        cancel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("CONIFIRM");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, 220, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/IMG/profile.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/IMG/home.jpg"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/IMG/back.jpg"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 10, 60, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/IMG/msg.jpg"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 640, -1, -1));

        body.setText("body Class");
        body.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyActionPerformed(evt);
            }
        });
        getContentPane().add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        bootcamp.setText("bootcamp Class");
        bootcamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bootcampActionPerformed(evt);
            }
        });
        getContentPane().add(bootcamp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        zumba.setText("zumba Class");
        zumba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zumbaActionPerformed(evt);
            }
        });
        getContentPane().add(zumba, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("choose the time period : ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        AM.setText("AM");
        AM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMActionPerformed(evt);
            }
        });
        getContentPane().add(AM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        PM.setText("PM");
        PM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PMActionPerformed(evt);
            }
        });
        getContentPane().add(PM, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, -1, -1));

        spinning.setText("spinning Class");
        spinning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spinningActionPerformed(evt);
            }
        });
        getContentPane().add(spinning, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        ABS.setText("ABS Class");
        ABS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABSActionPerformed(evt);
            }
        });
        getContentPane().add(ABS, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        cardio.setText("cardio Class");
        cardio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardioActionPerformed(evt);
            }
        });
        getContentPane().add(cardio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/IMG/cancel class.JPG"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 360, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        new userpage().setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        new MemberMenu().setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        new MemberMenu().setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        new CostumreService().setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void bodyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bodyActionPerformed

    private void bootcampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bootcampActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bootcampActionPerformed

    private void zumbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zumbaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zumbaActionPerformed

    private void AMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AMActionPerformed

    private void PMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PMActionPerformed

    private void spinningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spinningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spinningActionPerformed

    private void ABSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ABSActionPerformed

    private void cardioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardioActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
          String result = "";
        if (PM.isSelected()) {
            if (spinning.isSelected()) {
                result = GymSystem.member.cancelClassMEM(102);
            }
            if (ABS.isSelected()) {
                result = GymSystem.member.cancelClassMEM(202);
            }
            if (cardio.isSelected()) {
                result = GymSystem.member.cancelClassMEM(302);
            }
            if (body.isSelected()) {
                result = GymSystem.member.cancelClassMEM(602);
            }
            if (bootcamp.isSelected()) {
                result = GymSystem.member.cancelClassMEM(402);
            }
            if (zumba.isSelected()) {
                result = GymSystem.member.cancelClassMEM(502);
            }
        }
        //AM 
        if (AM.isSelected()) {
            if (spinning.isSelected()) {
                result = GymSystem.member.cancelClassMEM(101);
            }
            if (ABS.isSelected()) {
                result = GymSystem.member.cancelClassMEM(201);
            }
            if (cardio.isSelected()) {
                result = GymSystem.member.cancelClassMEM(301);
            }
            if (body.isSelected()) {
                result = GymSystem.member.cancelClassMEM(601);
            }
            if (bootcamp.isSelected()) {
                result = GymSystem.member.cancelClassMEM(401);
            }
            if (zumba.isSelected()) {
                result = GymSystem.member.cancelClassMEM(501);
            }
        }
        if (!result.isEmpty()) {
             Detiles3 s = new  Detiles3(1);
        s.setVisible(true);
        s.setLocationRelativeTo(null);
        this.dispose();}
		       

        //jLabel7MouseClicked(null);
   
                                          
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ABS;
    private javax.swing.JRadioButton AM;
    private javax.swing.JRadioButton PM;
    private javax.swing.JRadioButton body;
    private javax.swing.JRadioButton bootcamp;
    private javax.swing.JButton cancel;
    private javax.swing.JRadioButton cardio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton spinning;
    private javax.swing.JRadioButton zumba;
    // End of variables declaration//GEN-END:variables
}
