/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BackEnd.CLASS;
import BackEnd.Member;
import java.util.ArrayList;

/**
 *
 * @author HP
 */
public class Detiles4 extends javax.swing.JFrame {

    private int userType = 0;

    public Detiles4(int userType) {
        this.userType = userType;
        String str;
        initComponents();
        if (userType == 1) {
            str = "------------------------------------------------------------" + "\n";
            str += "Name\tPeriod\tTrainer" + "\n";
            str += "------------------------------------------------------------" + "\n";
            ArrayList<CLASS> classes = GymSystem.member.getClasses();

            for (CLASS classe : classes) {
                str += String.format("%-24s%-24s%s\n", classe.getName().trim(), classe.getPeriod(), classe.getTrainer().getName());
            }
        } else {
            str = "------------------------------------------------------------" + "\n";
            str += "Name\tPeriod" + "\n";
            str += "------------------------------------------------------------" + "\n";
            ArrayList<CLASS> classes = GymSystem.trainer.getClasses();

            for (CLASS classe : classes) {
                str += String.format("%-24s%-24s\n", classe.getName().trim(), classe.getPeriod());
            }

        }
        Schedule.setText(str);

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Schedule = new javax.swing.JTextArea();
        UserPage = new javax.swing.JLabel();
        HomeBUttom = new javax.swing.JLabel();
        backButton = new javax.swing.JLabel();
        Service = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/IMG/profile.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Schedule.setEditable(false);
        Schedule.setColumns(20);
        Schedule.setRows(5);
        jScrollPane1.setViewportView(Schedule);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 270, 330));

        UserPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/IMG/profile.png"))); // NOI18N
        UserPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserPageMouseClicked(evt);
            }
        });
        getContentPane().add(UserPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        HomeBUttom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/IMG/home.jpg"))); // NOI18N
        HomeBUttom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBUttomMouseClicked(evt);
            }
        });
        getContentPane().add(HomeBUttom, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/IMG/back.jpg"))); // NOI18N
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Service.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/IMG/msg.jpg"))); // NOI18N
        Service.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ServiceMouseClicked(evt);
            }
        });
        getContentPane().add(Service, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 680, 90, 80));

        jButton1.setBackground(new java.awt.Color(139, 184, 139));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CONIFIRM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 220, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/IMG/todaySchedulr.JPG"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 350, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        new userpage().setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void UserPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserPageMouseClicked
        new userpage().setVisible(true);
    }//GEN-LAST:event_UserPageMouseClicked

    private void HomeBUttomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBUttomMouseClicked
        new MemberMenu().setVisible(true);
    }//GEN-LAST:event_HomeBUttomMouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        MemberMenu us = new MemberMenu();
        us.setVisible(true);
        us.setLocationRelativeTo(null);
    }//GEN-LAST:event_backButtonMouseClicked

    private void ServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServiceMouseClicked
        new CostumreService().setVisible(true);
    }//GEN-LAST:event_ServiceMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  classConn cp= new classConn();
		cp.setVisible(true);
        cp.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HomeBUttom;
    private javax.swing.JTextArea Schedule;
    private javax.swing.JLabel Service;
    private javax.swing.JLabel UserPage;
    private javax.swing.JLabel backButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
